root:
  - changed-files:
      - any-glob-to-any-file: '*'
  
source:
  - changed-files:
      - any-glob-to-any-file: "src/main/java/**"
      - all-globs-to-all-files: '!src/docs/*'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "src/test/**"

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - "src/main/resources/**"
          - "application*.yml"
          - "application*.properties"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "src/main/resources/db/**"
          - "src/main/resources/migration/**"

build:
  - changed-files:
      - any-glob-to-any-file: 
          - "pom.xml"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"  
