image: maven:3.9.12-eclipse-temurin-25

stages:
  - build
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -e -V"

cache:
  key: maven
  paths:
    - .m2/repository

before_script:
  - chmod +x mvnw || true

# -----------------------
# Build (compile only)
# -----------------------
build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean verify

    # Debug utile
    - find . -name jacoco.exec -ls
    - ls -l co-drivin-test-report/target/site/jacoco-aggregate
    - cat co-drivin-test-report/target/site/jacoco-aggregate/jacoco.csv

    - |
      awk -F"," '{
        instr += $4 + $5;
        cov   += $5
      } END {
        printf("Total coverage: %.2f%%\n", 100*cov/instr)
      }' co-drivin-test-report/target/site/jacoco-aggregate/jacoco.csv

  artifacts:
    when: on_success
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "**/target/site/jacoco/jacoco.xml"
  coverage: '/Total coverage:\s+(\d+\.\d+)%/'

# -----------------------
# Package (JAR)
# -----------------------
package:
  stage: package
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - api/target/*.jar
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_TAG
